### PR TITLE
chore: remove lockfile from .gitignore and commit pnpm-lock.yaml to avoid docker build failure

### PR DESCRIPTION
**Pull request by aiyogg**
To avoid build errors, we must generate a lockfile before running ⁠`docker build`. This is necessary because the `⁠pnpm-lock.yaml` file is listed in the `⁠.gitignore`.

### CODE REVIEW

**Comment by aiyogg** [comment]
In fact, putting the lockfile in the repo can effectively avoid various build errors caused by dependency issues. Do you think the lockfile should be removed from .gitignore? Or should we regenerate the lockfile in this way?

**Comment by zzzgydi** [comment]
I think it's better to remove lockfile from `.gitignore`.

**Comment by aiyogg** [comment]
> I think it's better to remove lockfile from `.gitignore`.

I also think it’s better to do it this way. I have already updated this PR and committed the lockfile to the repository.

**Comment by zzzgydi** [comment]
LGTM

**Pull request merged**
